"""fractal_kleinian.py — Kleinian group limit set, category B.

Standalone module — no circular import with fractal_explorer_v2.
Imported by fractal_explorer_v2 at the bottom and registered into PAGE_CLASSES["B"].

Renders the limit set of a Schottky group generated by four circle inversions
about circles centered at ±1 and ±i, each with configurable radius r.

The limit set is the invariant set under all group elements — it appears as
a fractal Cantor dust at the boundary between the basins of attraction.
Colouring by escape count (identical machinery to escape-time fractals).
"""
from __future__ import annotations

import colorsys

import numpy as np
import pygame

_BG = (10, 10, 10)


def _hsv_palette(n: int, hue_offset: float = 0.55) -> np.ndarray:
    """Return (n+1, 3) uint8; index 0 = background (black)."""
    arr = np.zeros((n + 1, 3), dtype=np.uint8)
    for i in range(n):
        h = (hue_offset + i / max(n, 1)) % 1.0
        r, g, b = colorsys.hsv_to_rgb(h, 0.82, 0.88)
        arr[i + 1] = (int(r * 255), int(g * 255), int(b * 255))
    return arr


class KleinianLimitSet:
    """Schottky-group limit set via iterated circle inversion.

    Four generating circles centred at ±1 and ±1i, each with radius ``r``.
    Escape-time colouring: at each pixel, apply inversions up to max_iter times
    and record when |z| escapes beyond escape_radius.  The limit set (where
    orbits never escape) appears as the in-set region coloured by escape depth.

    Progressive rendering: one band of ``rows_per_frame`` rows per update().
    """

    name = "Kleinian Limit Set"
    info = "Schottky group circle inversion · 4 generators at ±1, ±i · Kleinian limit set"
    category = "B"
    x_range = (-2.5, 2.5)
    y_range = (-2.0, 2.0)
    max_iter = 48
    rows_per_frame = 12
    escape_radius = 6.0

    def __init__(self, w: int, h: int, r: float = 0.35):
        self.w = w
        self.h = h
        self.r = r
        self._initialised = False
        # Fixed circle centres: ±1 on real axis, ±1i on imaginary axis
        self._centers = np.array([1.0, -1.0, 0.0, 0.0])  # real parts
        self._centers_imag = np.array([0.0, 0.0, 1.0, -1.0])  # imag parts

    def reset(self) -> None:
        self.surface = pygame.Surface((self.w, self.h))
        self.surface.fill(_BG)
        self.row = 0
        self.palette = _hsv_palette(self.max_iter)
        self._initialised = True

    def _ensure_init(self) -> None:
        if not self._initialised:
            self.reset()

    def ensure_init(self) -> None:
        self._ensure_init()

    def update(self, frame: int) -> None:  # noqa: ARG002
        self._ensure_init()
        if self.row >= self.h:
            return
        y1 = min(self.h, self.row + self.rows_per_frame)
        self._render_rows(self.row, y1)
        self.row = y1

    def _render_rows(self, y0: int, y1: int) -> None:
        x0, x1 = self.x_range
        ymin, ymax = self.y_range
        xs = np.linspace(x0, x1, self.w)
        ys = np.linspace(ymin, ymax, self.h)[y0:y1]
        cx, cy = np.meshgrid(xs, ys)
        z = cx + 1j * cy

        r2 = self.r * self.r
        centres = self._centers + 1j * self._centers_imag
        # Schottky circle pairings: C1(+1)↔C2(-1), C3(+i)↔C4(-i)
        # Möbius generator Ti maps int(Ci) to ext(partner): z → partner + r²/(z − ci)
        partners = np.array([centres[1], centres[0], centres[3], centres[2]])

        out = np.zeros(z.shape, dtype=np.int32)
        escaped = np.zeros(z.shape, dtype=bool)

        for i in range(self.max_iter):
            moved = np.zeros(z.shape, dtype=bool)
            for k in range(4):
                c = centres[k]
                diff = z - c
                inside = (np.abs(diff) < self.r) & ~escaped & ~moved
                # Guard against degenerate denominator; safe_diff never used where ~inside
                safe_diff = np.where(np.abs(diff) > 1e-12, diff, 1.0 + 0j)
                z = np.where(inside, partners[k] + r2 / safe_diff, z)
                moved |= inside

            # Escape = reached the fundamental domain (outside all four circles)
            new_escaped = ~moved & ~escaped
            out[new_escaped] = i + 1
            escaped |= new_escaped

            if escaped.all():
                break

        rgb = self.palette[np.clip(out, 0, self.max_iter)]
        sub = pygame.surfarray.make_surface(rgb.transpose(1, 0, 2))
        self.surface.blit(sub, (0, y0))

    def draw(self, screen: pygame.Surface) -> None:
        self._ensure_init()
        screen.blit(self.surface, (0, 0))

    def tweak_param(self, delta: float) -> None:
        pass

    def reset_params(self) -> None:
        pass

    def get_param_display(self) -> str:
        return f"r = {self.r:.3f}"
